### ISSUE TITLE
PHP Fatal Error trying to reproduce the instructions from the README

### ISSUE THREAD

**Issue by brice-morin** [PavelJurasek/PHPWander#5]
I have installed PHP 7.2.6, Composer and PHPWander on my Windows machine.

When running `./bin/phpwander analyse tests/cases/ --autoload`, I get this error:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPStan\Analyser\Error::__construct() must be of the type string, null given, called in ..../PHPWander\src\Analyser\Analyser.php on line 205 and defined in ....\PHPWander\vendor\phpstan\phpstan\src\Analyser\Error.php:20
```

I guess this has to do [with the funny Windows `\` in paths instead of proper `/`](https://stackoverflow.com/questions/6510468/is-there-a-way-to-force-php-on-windows-to-provide-paths-with-forward-slashes)

**Comment by PavelJurasek** [comment]
Hello, thank you for the report! 
I replaced all occurrences of hard-coded directory separators in ef1723d644d37ec2a00e80658098599ad8919057, but I cannot test it on Windows myself. I'll be happy for further feedback so that it can be resolved.

**Comment by brice-morin** [comment]
Great, thanks! This seems to work. At least I was able to run `tests/cases/0`

I however have some issues for the cases relying on msqli (but I will create a separate issue, so we can consider this one closed).
