### ISSUE TITLE
AutoLoad Doesn't Exist

### ISSUE THREAD

**Issue by KevinCooper** [PavelJurasek/PHPWander#8]
https://github.com/PavelJurasek/PHPWander/blob/3bd25290a7e47cc18ca567eb66bbde7646fc12dc/bin/phpwander#L15

This relative dependency doesn't exist after following the install instructions making it so the code does not run.

**Comment by PavelJurasek** [comment]
Did you run ```composer install``` in command line?

**Comment by PavelJurasek** [comment]
Also be aware that currently I don't have time to develop this project and most likely it won't work. This project relies on upgrading the code up-to-date with phpstan/phpstan, but this has been neglected for over a year.
